export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const GET_USERS_PROGRESS = 'GET_USERS_PROGRESS';

export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_ERROR = 'UPDATE_USERS_ERROR';
export const UPDATE_USERS_PROGRESS = 'UPDATE_USERS_PROGRESS';

export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
export const ADD_USER_PROGRESS = "ADD_USER_PROGRESS";

export const SORT_USER_SUCCESS = 'SORT_USER_SUCCESS';
export const SORT_USER_ERROR = 'SORT_USER_ERROR';
export const SORT_USER_PROGRESS = 'SORT_USER_PROGRESS';

export const GROUP_USERS_SUCCESS = 'GROUP_USERS_SUCCESS';
export const GROUP_USERS_ERROR = 'GROUP_USERS_ERROR';
export const GROUP_USERS_PROGRESS = 'GROUP_USERS_PROGRESS';

export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_ERROR = 'GET_GROUPS_ERROR';
export const GET_GROUPS_PROGRESS = 'GET_GROUPS_PROGRESS';